{
 "title": "Varnish",
 "description": "A dashboard to use to debug a running varnish node. Easily track requests, cache hits, network i/o, sessions, threads, bans, ban lurker and the ban list size",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "varnish_node", "label": "node", "query": { "query": "label_values(varnish_up,node)" } }
  ]
 },
 "panels": [
  { "title": "Özet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (max by (node) (rate(node_cpu_seconds_total{mode=\"idle\",node=~\"$varnish_node\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Hafıza Kullanımı",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{node=~\"^($varnish_node).*\"} + node_memory_Cached_bytes{node=~\"^($varnish_node).*\"} + node_memory_Buffers_bytes{node=~\"^($varnish_node).*\"}) / node_memory_MemTotal_bytes{node=~\"^($varnish_node).*\"}))[$__range]",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Toplam Obje",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_n_object{node=~\"^($varnish_node).*\"}[$__range]",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(varnish_main_client_req{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(varnish_main_backend_req{node=~\"^$varnish_node.*\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(varnish_main_cache_hit{node=~\"^($varnish_node).*\"})[$__rate_interval] / irate(varnish_main_client_req{node=~\"^($varnish_node).*\"})[$__rate_interval]",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_vmods{node=~\"^($varnish_node).*\"}[$__rate_interval]",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_uptime{node=~\"^($varnish_node).*\"}[$__rate_interval]",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Sistem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "cluster" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{node=~\"^$varnish_node$\",mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{node}} {{mode}}"
    }
   ]
  },
  {
   "title": "Hafıza Kullanımı",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node-exporter',node=~'^$varnish_node$'}[$__range] - node_memory_MemFree_bytes{job='node-exporter',node=~'^$varnish_node$'}[$__range] - node_memory_Buffers_bytes{job='node-exporter',node=~'^$varnish_node$'}[$__range] - node_memory_Cached_bytes{job='node-exporter',node=~'^$varnish_node$'}[$__range]",
     "legendFormat": "{{node }} Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='node-exporter',node=~'^$varnish_node$'}",
     "legendFormat": "{{node }} Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='node-exporter',node=~'^$varnish_node$'}",
     "legendFormat": "{{node }} Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='node-exporter',node=~'^$varnish_node$'}",
     "legendFormat": "{{node }} Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=~\"^(nvme).*\",node=~\"$varnish_node\"}[$__rate_interval])",
     "legendFormat": "READ: {{node}} {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=~\"^(nvme).*\",node=~\"$varnish_node\"}[$__rate_interval])",
     "legendFormat": "WRITE: {{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Kullanımı",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{device=~\"/dev/(mapper|nvme).*\", node=~\"$varnish_node\"}[$__range] / node_filesystem_size_bytes{device=~\"/dev/(mapper|nvme).*\", node=~\"$varnish_node\"}[$__range]",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Yük durumu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{node=~\"^$varnish_node$\"}[$__range]",
     "legendFormat": "{{node }} Load-1"
    },
    {
     "expr": "node_load5{node=~\"^$varnish_node$\"}[$__range]",
     "legendFormat": "{{node }} Load-5"
    },
    {
     "expr": "node_load15{node=~\"^$varnish_node$\"}[$__range]",
     "legendFormat": "{{node }} Load-15"
    }
   ]
  },
  {
   "title": "Ağ Kullanımı",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum without(device) (rate(node_network_receive_bytes_total{node=~\"^$varnish_node$\"}[$__rate_interval]))*8",
     "legendFormat": "{{node}} alınan"
    },
    {
     "expr": "- sum without(device) (rate(node_network_transmit_bytes_total{node=~\"^$varnish_node$\"}[$__rate_interval]))*8",
     "legendFormat": "{{node}} gönderilen"
    }
   ]
  },
  { "title": "İstekler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{node=~\"^($varnish_node).*\"}[$__rate_interval]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_main_backend_req{node=~\"^($varnish_node).*\"}[$__rate_interval]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_main_fetch_total{node=~\"^($varnish_node).*\"}[$__rate_interval]))",
     "legendFormat": "fetched objects"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(varnish_main_cache_hit{node=~\"^($varnish_node).*\"}[$__rate_interval]) / rate(varnish_main_client_req{node=~\"^($varnish_node).*\"}[$__rate_interval]))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hit{node=~\"^($varnish_node).*\"}[$__rate_interval]) / rate(varnish_main_client_req{node=~\"^($varnish_node).*\"}[$__rate_interval])))",
     "legendFormat": "cache miss %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hitpass{node=~\"^($varnish_node).*\"}[$__rate_interval]) / rate(varnish_main_client_req{node=~\"^($varnish_node).*\"}[$__rate_interval])))",
     "legendFormat": "cache hit pass %"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{node=~\"^($varnish_node).*\"}[5m]) + irate(varnish_main_s_resp_bodybytes{node=~\"^($varnish_node).*\"}[5m]))*8",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{node=~\"^($varnish_node).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{node=~\"^($varnish_node).*\"}[5m]))*8",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{node=~\"^($varnish_node).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{node=~\"^($varnish_node).*\"}[5m])) by (backend)*8",
     "legendFormat": "backend {{ backend }}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{node=~\"^($varnish_node)\"}[$__rate_interval])) by (node)",
     "legendFormat": "expired | {{node}}"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{node=~\"^($varnish_node)\"}[$__rate_interval])) by (node)",
     "legendFormat": "LRU moved | {{node}}"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{node=~\"^($varnish_node)\"}[$__rate_interval])) by (node)",
     "legendFormat": "LRU nuked | {{node}}"
    },
    {
     "expr": "sum(varnish_sma_g_bytes{type=~\"hafiza|s0\", node=~\"^($varnish_node)\"}[$__rate_interval]) by (node)",
     "legendFormat": "mem used | {{node}}"
    }
   ]
  },
  { "title": "Bağlantılar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Backend Connections (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(varnish_main_backend_conn{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. success {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_recycle{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. recycles  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_reuse{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. reuses  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_fail{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. failures  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_unhealthy{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. not attempted  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_busy{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. too many  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_req{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend requests made  {{ node }}"
    },
    {
     "expr": "irate(varnish_main_backend_retry{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Backend conn. retry  {{ node }}"
    },
    {
     "expr": "irate(varnish_backend_conn{node=~\"^($varnish_node)\"}[1m])",
     "legendFormat": "Concurrent connections to backend - {{ backend }} - {{ node }}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (irate(varnish_main_sessions{node=~\"^($varnish_node).*\"}[$__rate_interval]))",
     "legendFormat": "session - {{type}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(varnish_main_threads_created{node=~\"^($varnish_node).*\"})[$__rate_interval]",
     "legendFormat": "Threads created - {{ node }}"
    },
    {
     "expr": "rate(varnish_main_threads_destroyed{node=~\"^($varnish_node).*\"})[$__rate_interval]",
     "legendFormat": "Threads destroyed - {{ node }}"
    },
    {
     "expr": "rate(varnish_main_threads_failed{node=~\"^($varnish_node).*\"})[$__rate_interval]",
     "legendFormat": "Thread creation failed - {{ node }}"
    },
    {
     "expr": "rate(varnish_main_threads_limited{node=~\"^($varnish_node).*\"})[$__rate_interval]",
     "legendFormat": "Max Threads hit - {{ node }}"
    },
    {
     "expr": "varnish_main_threads{node=~\"^($varnish_node).*\"}",
     "legendFormat": "Total number of threads - {{ node }}"
    },
    {
     "expr": "varnish_main_thread_queue_len{node=~\"^($varnish_node).*\"}",
     "legendFormat": "Length of session queue waiting for threads - {{ node }}"
    },
    {
     "expr": "varnish_main_pools{node=~\"^($varnish_node).*\"}",
     "legendFormat": "Number of thread pools - {{ node }}"
    }
   ]
  },
  {
   "title": "Bans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bans",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "varnish_main_bans{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Count of Bans"
      },
      {
       "expr": "varnish_main_bans_completed{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Number of bans marked 'completed'"
      },
      {
       "expr": "varnish_main_bans_deleted{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Bans deleted"
      },
      {
       "expr": "varnish_main_bans_dups{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Bans superseded by other bans"
      },
      {
       "expr": "varnish_main_bans_obj{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Number of bans using obj.*"
      },
      {
       "expr": "varnish_main_bans_obj_killed{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Objects killed by bans (lookup)"
      }
     ]
    },
    {
     "title": "Size of Ban Lists",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "varnish_main_bans_persisted_bytes{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Bytes used by the persisted ban lists"
      },
      {
       "expr": "varnish_main_bans_persisted_fragmentation{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Extra bytes in persisted ban lists due to fragmentation"
      }
     ]
    },
    {
     "title": "Ban Lurker",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "varnish_main_bans_lurker_contention{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Lurker gave way for lookup"
      },
      {
       "expr": "varnish_main_bans_lurker_obj_killed{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Objects killed by bans (lurker)"
      },
      {
       "expr": "varnish_main_bans_lurker_tested{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Bans tested against objects (lurker)"
      },
      {
       "expr": "varnish_main_bans_lurker_tests_tested{node=~\"^($varnish_node).*\"}",
       "legendFormat": "Ban tests tested against objects (lurker)"
      }
     ]
    }
   ]
  },
  { "title": "Cevap Süreleri", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Desktop Backend  Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Average Response Time (hit)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Average Response Time (miss)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND -http_method.keyword: \"HEAD\" AND cache_status:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Desktop Backend Bot Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Average Response Time (hit)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "ua.name: Googlebot AND varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Average Response Time (miss)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "ua.name: Googlebot AND varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND -http_method.keyword: \"HEAD\" AND cache_status:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Desktop Backend Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "HIT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status.keyword:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MISS",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status.keyword:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Desktop Backend  Bot Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "HIT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "known-bot.keyword: \"true\" AND varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status.keyword:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MISS",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "known-bot.keyword: \"true\" AND varnish_backend.keyword: \"turbo-desktop.kbnt-prod.cimri.com\" AND cache_status.keyword:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mobile Backend  Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Average Response Time (hit)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Average Response Time (miss)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND NOT http_method.keyword: \"HEAD\" AND cache_status:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mobile Backend Bot Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Average Response Time (hit)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ua.name: Googlebot AND varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Average Response Time (miss)",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "ua.name: Googlebot AND varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND -http_method.keyword: \"HEAD\" AND cache_status:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mobile Backend Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "HIT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status.keyword:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MISS",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status.keyword:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mobile Backend  Bot Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "HIT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "known-bot.keyword: \"true\" AND varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status.keyword:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MISS",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "known-bot.keyword: \"true\" AND varnish_backend.keyword: \"turbo-mobile.kbnt-prod.cimri.com\" AND cache_status.keyword:\"miss\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voyager Backend Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Average Response Time (hit)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"voyager.kbnt-prod.cimri.com\" AND cache_status:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Average Response Time (miss)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "response_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "varnish_backend.keyword: \"voyager.kbnt-prod.cimri.com\" and -http_method.keyword: \"HEAD\" AND cache_status:\"miss\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voyager Backend Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "HIT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "varnish_backend.keyword: \"voyager.kbnt-prod.cimri.com\" AND cache_status.keyword:\"hit\" AND NOT http_method.keyword: \"HEAD\" AND agent.name: \"$varnish_node\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MISS",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:145",
       "field": "backend_processing_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "varnish_backend.keyword: \"voyager.kbnt-prod.cimri.com\" AND cache_status.keyword:\"miss\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Varnish 8 Internals (VCP, Waiter, Locks)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Waiter Actions (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(varnish_waiter_action{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{id}} - action"
    },
    {
     "expr": "irate(varnish_waiter_remclose{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{id}} - remclose"
    },
    {
     "expr": "irate(varnish_waiter_timeout{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{id}} - timeout"
    }
   ]
  },
  {
   "title": "Waiter Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "varnish_waiter_conns{node=~\"^($varnish_node).*\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "VCP Ref Hits/Misses (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(varnish_vcp_ref_hit{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "hit"
    },
    {
     "expr": "irate(varnish_vcp_ref_miss{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Lock Operations (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(varnish_lock_created{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{target}} - created"
    },
    {
     "expr": "irate(varnish_lock_dbg_busy{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{target}} - dbg_busy"
    },
    {
     "expr": "irate(varnish_lock_dbg_try_fail{node=~\"^($varnish_node).*\"}[$__rate_interval])",
     "legendFormat": "{{target}} - try_fail"
    }
   ]
  },
  {
   "title": "SMU (Umem Stevedore) Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "varnish_smu_g_bytes{node=~\"^($varnish_node).*\"}",
     "legendFormat": "{{type}} - bytes"
    },
    {
     "expr": "varnish_smu_g_space{node=~\"^($varnish_node).*\"}",
     "legendFormat": "{{type}} - free space"
    }
   ]
  }
 ]
}